
export enum Aggregate {
    VALUES = 'values' as any,
    COUNT = 'count' as any,
    VALID = 'valid' as any,
    MISSING = 'missing' as any,
    DISTINCT = 'distinct' as any,
    SUM = 'sum' as any,
    MEAN = 'mean' as any,
    AVERAGE = 'average' as any,
    VARIANCE = 'variance' as any,
    VARIANCEP = 'variancep' as any,
    STDEV = 'stdev' as any,
    STDEVP = 'stdevp' as any,
    MEDIAN = 'median' as any,
    Q1 = 'q1' as any,
    Q3 = 'q3' as any,
    MODESKEW = 'modeskew' as any,
    MIN = 'min' as any,
    MAX = 'max' as any,
    ARGMIN = 'argmin' as any,
    ARGMAX = 'argmax' as any,
}

export const AGGREGATE_OPS = [
    Aggregate.VALUES,
    Aggregate.COUNT,
    Aggregate.VALID,
    Aggregate.MISSING,
    Aggregate.DISTINCT,
    Aggregate.SUM,
    Aggregate.MEAN,
    Aggregate.AVERAGE,
    Aggregate.VARIANCE,
    Aggregate.VARIANCEP,
    Aggregate.STDEV,
    Aggregate.STDEVP,
    Aggregate.MEDIAN,
    Aggregate.Q1,
    Aggregate.Q3,
    Aggregate.MODESKEW,
    Aggregate.MIN,
    Aggregate.MAX,
    Aggregate.ARGMIN,
    Aggregate.ARGMAX,
];

export const SHARED_DOMAIN_OPS = [
    Aggregate.MEAN,
    Aggregate.AVERAGE,
    Aggregate.STDEV,
    Aggregate.STDEVP,
    Aggregate.MEDIAN,
    Aggregate.Q1,
    Aggregate.Q3,
    Aggregate.MIN,
    Aggregate.MAX,
];

// TODO: move supportedTypes, supportedEnums from schema to here
